import Head from 'next/head';
import { useEffect, useState } from 'react';
import { getData } from '../../../../__lib__/helpers/HttpService';
import Banner from '../banner/Banner';
import CardRow from '../cardrow/CardRow';
import Cards from '../cards/Cards';
import Layout from '../layout';
import TrustedCompany from '../trustedCompanies/TrustedCompany';


export default function Home() {
    const [jobs, setJobs] = useState([])
    useEffect(() => {
        getData('/jobs')
        .then(res => setJobs(res))
    }, [])
    console.log(jobs)
  return (  
    <>
      <Head>
        <title>Talentdrop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner />
        <TrustedCompany />
        <Cards>
           {
               jobs.length > 0 && jobs.map((job, i) => <CardRow key={i} job={job} />)
            
           }
        </Cards>
      </Layout>
    </>
  );
}
