import Head from 'next/head';
import Banner from '../src/components/banner/Banner';
import Cards from '../src/components/cards/Cards';
import Layout from '../src/components/layout';
import TrustedCompany from '../src/components/trustedCompanies/TrustedCompany';

export default function Home() {
  return (
    <>
      <Head>
        <title>Talentdrop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner />
        <TrustedCompany />
        <Cards />
      </Layout>
    </>
  );
}
